# Generated by Django 3.0.4 on 2021-05-24 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoubanMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_url', models.CharField(max_length=256)),
                ('movie_title', models.CharField(max_length=64)),
                ('movie_keywords', models.TextField()),
                ('movie_description', models.TextField()),
                ('movie_directors', models.TextField()),
                ('movie_actors', models.TextField()),
            ],
        ),
    ]
