# Generated by Django 3.0.4 on 2025-03-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movierecommendation', '0002_questionamswerkb'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=256)),
                ('doclist', models.TextField()),
            ],
        ),
    ]
