//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by client.rc
//
#define IDD_DIALOG_CLIENT               101
#define IDC_EDIT_ADDR                   1000
#define IDC_EDIT_SHOW                   1001
#define IDC_EDIT_SEND                   1002
#define IDC_BUTTON_CONNECT              1003
#define IDC_BUTTON_GETIP                1004

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1004
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
