;默认采用ML6.11汇编程序
DATAS SEGMENT
    MESS	DB 	'Hello,World!' ,0DH,0AH,24H
DATAS ENDS

STACKS SEGMENT
    ;此处输入堆栈段代码
    DW 256 DUP(?)
STACKS ENDS

CODES SEGMENT
    ASSUME CS:CODES,DS:DATAS,SS:STACKS
BEGIN:
	MOV AX,DATAS
    MOV DS,AX
    ;此处输入代码段代码
    MOV DX,OFFSET MESS
    
    MOV AH,9
    INT 21H
    MOV AH,4CH
    INT 21H
CODES ENDS
    END BEGIN