# Generated by Django 4.2 on 2023-04-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoubanMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_url', models.CharField(max_length=256)),
                ('movie_title', models.CharField(max_length=64)),
                ('movie_keywords', models.TextField()),
                ('movie_description', models.TextField()),
                ('movie_directors', models.TextField()),
                ('movie_actors', models.TextField()),
            ],
        ),
    ]
