# Generated by Django 4.2 on 2023-04-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movierecommendation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoubanMovieIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_keyword', models.CharField(max_length=256)),
                ('movie_doclist', models.TextField()),
            ],
        ),
    ]
