# Generated by Django 4.2 on 2023-05-31 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movierecommendation', '0002_doubanmovieindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswerKB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
    ]
