# Generated by Django 4.2 on 2023-05-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movierecommendation', '0002_doubanmovieindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubanmovie',
            name='movie_category',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
