# Generated by Django 4.2 on 2025-03-18 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movierecommendation', '0003_doubanmovie_movie_category'),
        ('movierecommendation', '0003_questionanswerkb'),
    ]

    operations = [
    ]
