# Generated by Django 4.2 on 2025-03-18 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movierecommendation', '0004_merge_20250319_0051'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoubanMovie',
        ),
        migrations.DeleteModel(
            name='DoubanMovieIndex',
        ),
    ]
