# Generated by Django 4.2 on 2025-03-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movierecommendation', '0005_delete_doubanmovie_delete_doubanmovieindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=256)),
                ('doclist', models.TextField()),
            ],
        ),
    ]
